# Importing Libraries
import streamlit as st

# App
st.set_page_config(
    page_title="veCHR Checker",
    page_icon="icons/chr.png",
    layout="wide",
)

# Title
st.title("💬 About")

# Content
st.write(
    """## What is veCHR?
veCHR is 'CHR' locked for voting power.

## What is the utility of veCHR?
Voting on liquidity pools and directing $CHR emissions to them, while at the same time earning from swap fees and gauge bribes proportional to their vote on the liquidity pool(s).

## What do veCHR voters receive?
- Trading fees generated by the pool(s) they vote for
- Bribes deposited for the pools they vote for
- Weekly veCHR distribution (rebase)

## Why this Tracker?
This was created by me aka 🍓ALMIGHTY ABE🍓 to fill the gap of NFT marketplaces not showcasing Financial NFTs properly and making veNFT metadata user-friendly.

## Important Links
My Twitter: https://twitter.com/ALM1GHTYABE

Chronos's Twitter: [https://twitter.com/ChronosFi_](https://twitter.com/ChronosFi_)

Chronos's Discord: https://discord.gg/chronosfi

veChronos Collection: https://opensea.io/collection/vechronos-1

## Note
NFA, DYOR -- This web app is in beta, I am not responsible for any information on this webapp.

If you find any inaccuracies on this webapp feel free to reach out to me on Twitter. 

## If you like this project, you may buy me a cup of coffee ☕.
"""
)
st.code("0x5783Fb2f3d93364041d49097b66086703527AeaC")
